pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                echo "Comp-Wolf_Way to Reinvent Yourself"
                sh 'echo using shell within Jenkinsfile'
                echo 'not using shell in the Jenkinsfile'
            }
        }
    }
}
