#! /bin/bash

yum update
yum install git -y
git clone https://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@github.com/clarusway-aws-devops/project-207-Nihatcan17.git
amazon-linux-extras install docker -y
systemctl start docker
systemctl enable docker
systemctl status docker
usermod -a -G docker ec2-user
newgrp docker
curl -L "https://github.com/docker/compose/releases/download/v2.12.2/docker-compose-$(uname -s)-$(uname -m)" \
-o /usr/local/bin/docker-compose
chmod +x /usr/local/bin/docker-compose