apiVersion: v1
kind: Service   
metadata:
  name: mysql-service
  labels:
    app: mysql-service
spec:
  type: ClusterIP  
  ports:
  - port: 3306
    targetPort: 3306
  selector:
    name: mysql
    app: phonebook 